title: "Xebia Essentials"
description: "The Xebia Essentials is a deck of flash cards about software craftsmanship."

destination: docs
category_title_prefix: ""

card_types:
  - name: craftsmanship
    colour: "#F80068"
  - name: collaboration
    colour: "#FC7A25"
  - name: realisation
    colour: "#107FD5"
  - name: testing
    colour: "#6DC726"
  - name: other
    colour: "#4C2F5C"

url: "https://essentials.xebia.com/"
img: "//essentials.xebia.com/img"
mailto: "essentials@xebia.com"

permalink: pretty
exclude: ['README.md', '*.iml']